name: 'Send Payload to Pytest Testmon'
description: 'Dynamically build and send dispatch payload to trigger pytest testmon tests across multiple OS and Python versions'

inputs:
  repository_name:
    description: 'Repository name'
    required: true
    default: '7rikazhexde/python-project-sandbox'
  ghpages_branch:
    description: 'Target branch to fetch testmon data from'
    required: true
    default: 'gh_pages'
  os_list:
    description: 'Space-separated list of OS to run tests on'
    required: true
    default: 'ubuntu-latest macos-13 windows-latest'
  python_versions:
    description: 'Space-separated list of Python versions to test'
    required: true
    default: '3.11 3.12'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.12'

    - name: Install GitHub CLI
      run: sudo apt-get install -y gh
      shell: bash

    - name: Run Python script
      run: |
        python3 .github/send_payload.py
      shell: bash
      env:
        REPOSITORY_NAME: ${{ inputs.repository_name }}
        TARGET_BRANCH: ${{ inputs.ghpages_branch }}
        OS_LIST: ${{ inputs.os_list }}
        PYTHON_VERSIONS: ${{ inputs.python_versions }}
        GH_TOKEN: ${{ env.GH_TOKEN }}
