# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
