[tool.poetry]
name = "trial-test"
version = "0.2.117"
description = "An experimental project to test out various tools."
authors = ["7rikaz"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
tomlkit = "^0.11.8"
mdformat = "^0.7.16"
numpy = "^1.26.2"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.2"
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"
flake8-pyproject = "^1.2.3"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"
pytest-xdist = "^3.3.1"
pytest-html = "^4.1.1"
ruff = "^0.5.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]

[tool.black]
target-version = ['py310']

[tool.flake8]
ignore = ["E402","E501","W503"]

[tool.ruff]
# Check Rules
lint.select = ["E", "F", "I"]
# Ignore Error
lint.ignore = ["E402","E501"]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
lint.per-file-ignores = {}

# Assume Python 3.10.
target-version = "py310"

[tool.mypy]
files = ["calculator","tests","ci"]
python_version = "3.10"
strict = true
warn_return_any = false
ignore_missing_imports = true
scripts_are_modules = true

[tool.pytest.ini_options]
testpaths = ["tests",]
