[tool.poetry]
name = "trial-test"
version = "0.2.15"
description = "An experimental project to test out various tools."
authors = ["7rikaz_wsl1 <7rikaz.h785.stat2ltas41lcijad@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "trial_test"}]

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
numpy = "^1.24.3"
tomlkit = "^0.11.8"
mdformat = "^0.7.16"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.3.2"
flake8 = "^6.0.0"
black = "^23.3.0"
isort = "^5.12.0"
mypy = "^1.3.0"
flake8-pyproject = "^1.2.3"
pytest = "^7.3.1"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]

[tool.black]
target-version = ['py310']

[tool.flake8]
ignore = ["E402","E501","W503"]

[tool.mypy]
files = ["calculator","tests","ci"]
python_version = "3.10"
strict = true
warn_return_any = false
ignore_missing_imports = true
scripts_are_modules = true

[tool.pytest.ini_options]
testpaths = ["tests",]
