name: Create Release

# ワークフローの処理の流れ:
# 1. トリガー条件: 手動実行（workflow_dispatch）
#    - タグを指定（必須）
# 2. 指定されたタグが既にリリース済みかチェック
#    - リリース済みの場合はエラーで終了
# 3. リポジトリ名の取得
# 4. 変更ログの生成
#    - 前のタグから指定されたタグまでのコミットを取得
# 5. GitHubリリースの作成
#    - タグ名、リリース名（リポジトリ名を含む）、変更ログを含む

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from (leave empty for latest)'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if the tag is already released
        id: check_release
        run: |
          release=$(gh release view ${{ github.event.inputs.tag }} 2>/dev/null || echo "not_found")
          if [ "$release" != "not_found" ]; then
            echo "The tag ${{ github.event.inputs.tag }} is already released."
            exit 1
          fi

      - name: Get repository name
        id: get_repo_name
        run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          previous_tag=$(git describe --tags --abbrev=0 ${{ github.event.inputs.tag }}^)
          changelog=$(git log --pretty=format:"- %s" $previous_tag..${{ github.event.inputs.tag }})
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: ${{ steps.get_repo_name.outputs.repo_name }}-v${{ github.event.inputs.tag }}
          body: |
            Changes in this Release:
            ${{ steps.changelog.outputs.changelog }}

            For full changes, see the [comparison view](${{ github.server_url }}/${{ github.repository }}/compare/$previous_tag..${{ github.event.inputs.tag }})
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
