name: Create Release

# ワークフローの処理の流れ:
# 1. トリガー条件: 手動実行（workflow_dispatch）
#    - タグを指定（オプション、空の場合は最新のタグを使用）
# 2. 使用するタグの決定
#    - 入力が空の場合、最新のタグを取得
#    - 入力がある場合、指定されたタグを使用
# 3. 指定されたタグが既にリリース済みかチェック
#    - リリース済みの場合はエラーで終了
# 4. リポジトリ名の取得
# 5. 変更ログの生成
#    - 前のタグから指定されたタグまでのコミットを取得
# 6. GitHubリリースの作成
#    - タグ名、リリース名（リポジトリ名を含む）、変更ログを含む

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create release from (leave empty for latest)'
        required: false
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine tag to use
        id: get_tag
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]; then
            latest_tag=$(git describe --tags --abbrev=0)
            echo "tag=$latest_tag" >> $GITHUB_OUTPUT
            echo "Using latest tag: $latest_tag"
          else
            echo "tag=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "Using specified tag: ${{ github.event.inputs.tag }}"
          fi

      - name: Check if the tag is already released
        id: check_release
        run: |
          release=$(gh release view ${{ steps.get_tag.outputs.tag }} 2>/dev/null || echo "not_found")
          if [ "$release" != "not_found" ]; then
            echo "The tag ${{ steps.get_tag.outputs.tag }} is already released."
            exit 1
          fi

      - name: Get repository name
        id: get_repo_name
        run: echo "repo_name=${GITHUB_REPOSITORY#*/}" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          previous_tag=$(git describe --tags --abbrev=0 ${{ steps.get_tag.outputs.tag }}^)
          changelog=$(git log --pretty=format:"- %s" $previous_tag..${{ steps.get_tag.outputs.tag }})
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: ${{ steps.get_repo_name.outputs.repo_name }}-${{ steps.get_tag.outputs.tag }}
          body: |
            Changes in this Release:
            ${{ steps.changelog.outputs.changelog }}

            For full changes, see the [comparison view](${{ github.server_url }}/${{ github.repository }}/compare/$previous_tag..${{ steps.get_tag.outputs.tag }})
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
