name: Create Release

# ワークフローの処理の流れ:
# 1. 手動トリガーまたはversionup-and-release.ymlからのトリガーによるワークフロー開始
# 2. リポジトリのチェックアウト（全履歴を含む）
# 3. 指定されたバージョンの直前のタグを特定
# 4. 前回のタグから新しいバージョンまでの変更ログを生成
# 5. GitHubリリースの作成（タイトル、変更ログ、比較ビューリンクを含む）

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: get_previous_tag
        run: echo "previous_tag=$(git describe --tags --abbrev=0 v${{ github.event.inputs.version }}^)" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(git log --pretty=format:"- %s" ${{ steps.get_previous_tag.outputs.previous_tag }}..v${{ github.event.inputs.version }})
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: trial-test-v${{ github.event.inputs.version }}
          body: |
            Changes in this Release:
            ${{ steps.changelog.outputs.changelog }}

            For full changes, see the [comparison view](${{ github.server_url }}/${{ github.repository }}/compare/${{ steps.get_previous_tag.outputs.previous_tag }}..v${{ github.event.inputs.version }})
          draft: false
          prerelease: false
