name: Send Payload Action to Pytest Testmon

on:
  push:
    branches:
      - 'main'

jobs:
  test-and-send-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: Send Payload to Pytest Testmon
        uses: ./  # ローカルで定義されたアクションを使用
        with:
          repository_name: '7rikazhexde/python-project-sandbox'
          target_branch: 'ghpages'
          os_list: 'ubuntu-latest macos-13 windows-latest'
          python_versions: '3.11 3.12'
