name: Send Payload to Pytest Testmon

on:
  push:
    branches:
      - 'main'

jobs:
  send-dispatch:
    # Dependabotによる実行やバージョンバンプのコミットを除外
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        env:
          GH_TOKEN: ${{ secrets.SEND_PAYLOAD_PYTEST_TESTMON }}  # シークレット変数
        run: |
          gh api repos/7rikazhexde/trial-test/dispatches \
            -f event_type=test_pytest-cov-report_deploy_multi_os \
            -f client_payload[os][]=ubuntu-latest \
            -f client_payload[os][]=macos-13 \
            -f client_payload[os][]=windows-latest \
            -f client_payload[python_versions][]=3.11 \
            -f client_payload[python_versions][]=3.12
