name: Send Payload to Pytest Testmon

on:
  push:
    branches:
      - 'main'

jobs:
  send-dispatch:
    # Dependabotによる実行やバージョンバンプのコミットを除外
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
    runs-on: ubuntu-latest
    steps:
      - name: Send Dispatch Event
        env:
          GH_TOKEN: ${{ secrets.SEND_PAYLOAD_PYTEST_TESTMON }}
        run: |
          gh api repos/7rikazhexde/trial-test/dispatches \
            -f event_type=test \
            -f client_payload='{"os": ["ubuntu-latest", "macos-13", "windows-latest"], "python_versions": ["3.11", "3.12"]}'
