name: pytest-testmon Deploy Multi-OS

on:
  repository_dispatch:
    types:
      - test

jobs:
  test-and-deploy-testmon:
    strategy:
      matrix:
        os: ${{ github.event.client_payload.os }}
        python-version: ${{ github.event.client_payload.python_versions }}
    runs-on: ${{ matrix.os }}
    env:
      TZ: "Asia/Tokyo"
    permissions:
      contents: write
      pull-requests: write
    outputs:
      tests_executed: ${{ steps.pytest-testmon.outputs.tests_executed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      - name: Install poetry
        run: |
          pip install poetry
          echo "Poetry version: $(poetry --version)"

      - name: Install dependencies
        run: |
          poetry install
          echo "Installed dependencies"

      - name: Run pytest with testmon
        id: pytest-testmon
        run: |
          pytest --testmon

      - name: Upload testmondata
        if: ${{ steps.pytest-testmon.outputs.tests_executed == 'true' }}
        run: |
          echo "Uploading testmon data"

  deploy-testmon:
    needs: test-and-deploy-testmon
    if: contains(needs.test-and-deploy-testmon.result, 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Download testmon data
        uses: actions/download-artifact@v4.1.8
        with:
          path: downloaded-artifacts

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Git configuration set."

      - name: Deploy testmon data to GitHub Pages
        id: deploy_testmon
        run: |
          echo "Deploying testmon data to GitHub Pages..."
          git fetch origin ghpages:ghpages || git checkout -b ghpages
          git checkout ghpages

          changes_made=false
          for os in ${{ github.event.client_payload.os }}; do
            for python_version in ${{ github.event.client_payload.python_versions }}; do
              folder_name="testmon-data_${os}_python_${python_version}"
              artifact_folder="downloaded-artifacts/testmon-data-${os}-python-${python_version}"
              echo "Processing $os with Python $python_version..."
              if [ -f "${artifact_folder}/.testmondata" ]; then
                echo "Changes detected for $os with Python $python_version, updating..."
                mkdir -p $folder_name
                mv "${artifact_folder}/.testmondata" "$folder_name/.testmondata"
                git add $folder_name
                changes_made=true
              else
                echo "No testmon data found for $os with Python $python_version"
                echo "Contents of ${artifact_folder}:"
                ls -la "${artifact_folder}"
              fi
            done
          done

          if [ "$changes_made" = true ]; then
            echo "Changes made, committing and pushing..."
            git commit -m "Update testmon data on GitHub Pages"
            git push origin ghpages
            echo "deploy_status=updated" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "deploy_status=unchanged" >> $GITHUB_OUTPUT
          fi

      - name: List deployed files
        if: steps.deploy_testmon.outputs.deploy_status == 'updated'
        run: |
          git checkout ghpages
          echo "Deployed testmon data files:"
          find . -name ".testmondata"
          echo "Contents of ghpages branch:"
          ls -R

  trigger-other-workflows:
    needs: [test-and-deploy-testmon, deploy-testmon]
    if: needs.test-and-deploy-testmon.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pytest-cov workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-cov
          client-payload: '{"skip_tests": false}'

      - name: Trigger pytest-html workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-html
          client-payload: '{"skip_tests": false}'

      - name: Log workflow triggers
        run: |
          echo "Triggered pytest-cov and pytest-html workflows."
          echo "Check the Actions tab for these workflows to start."
