name: test and deploy multi

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "coverage"
  pull_request:

jobs:
  test_and_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: Check is main
        id: is_main
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ matrix.python-version }}" = "3.10" ];then
            echo "flag=1" >> $GITHUB_OUTPUT
          else
            echo "flag=0" >> $GITHUB_OUTPUT
          fi

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          if [[ "${{ matrix.os }}" == "macos-12" ]]; then
            echo "PATH=/Users/runner/.local/bin:$PATH" >> $GITHUB_ENV
          else
            echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          fi
      - name: Poetry setup
        run: poetry install

      - name: Run test with HTML report
        if: ${{ steps.is_main.outputs.flag == '1' }}
        run: |
          mkdir -p ${{ matrix.os }}
          poetry run pytest --html=${{ matrix.os }}/report_page.html

      - name: Commit HTML report to ghpages branch
        run: |
          git config --local user.email "33836132+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin ghpages:ghpages
          git checkout ghpages
          git add ${{ matrix.os }}/report_page.html
          git commit -m "Add pytest HTML report to ghpages for ${{ matrix.os }}"
          git push origin ghpages

      - name: line-notify
        if: ${{ steps.is_main.outputs.flag == '1' }}
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            Call "test_githubpages_deploy" from Github Action
            Env: ${{ matrix.os }} / ${{ matrix.python-version }}
            Check URL: https://7rikazhexde.github.io/trial-test/${{ matrix.os }}/report_page.html
