name: pytest-cov Report and Deploy Multi-OS

# ワークフローの処理の流れ:
# 1. トリガー条件:
#    - pytest-htmlレポートワークフローの完了
# 2. pytest-htmlワークフローが成功した場合のみ実行
# 3. 複数の環境（OS、Pythonバージョン）でのテスト実行
# 4. pytest-covを使用してカバレッジレポートを生成
# 5. カバレッジ結果のアップロード
# 6. GitHub Pagesへのデプロイ
# 7. デプロイしたレポートのURL生成
# 8. LINE通知の送信

on:
  workflow_run:
    workflows: ["pytest-html Report and Deploy Multi-OS"]
    types:
      - completed

jobs:
  test-and-coverage:
    if: github.event.workflow_run.conclusion == 'success'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}
    env:
      TZ: "Asia/Tokyo"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests with pytest-cov
        id: pytest-cov
        run: |
          mkdir -p htmlcov_${{ matrix.os }}
          poetry run pytest --cov=project_a --cov-report=html:htmlcov_${{ matrix.os }}
        shell: bash
      - name: Upload pytest-cov results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results-${{ matrix.os }}
          path: htmlcov_${{ matrix.os }}
        if: always()

  deploy:
    needs: test-and-coverage
    runs-on: ubuntu-latest
    if: success()
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download pytest-cov artifacts
        uses: actions/download-artifact@v4
      - name: Deploy to GitHub Pages
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch origin ghpages:ghpages || git checkout -b ghpages
          git checkout ghpages
          for os in ubuntu-latest macos-13 windows-latest; do
            mkdir -p $os
            if [ -d coverage-results-$os ]; then
              mv coverage-results-$os $os/htmlcov_$os
              git add $os/htmlcov_$os
            else
              echo "No pytest-cov report found for $os"
            fi
          done
          git commit -m "Add pytest-cov reports to GitHub Pages" || echo "No changes to commit"
          git push origin ghpages --force
      - name: Generate URL list
        id: generate_url_list
        run: |
          IFS='/' read -ra REPO_INFO <<< "$GITHUB_REPOSITORY"
          REPO_OWNER=${REPO_INFO[0]}
          REPO_NAME=${REPO_INFO[1]}
          URL_LIST=""
          for os in ubuntu-latest macos-13 windows-latest; do
            URL_LIST="${URL_LIST}pytest-cov: https://${REPO_OWNER}.github.io/${REPO_NAME}/${os}/htmlcov_${os}/index.html\n"
          done
          echo "url_list<<EOF" >> $GITHUB_OUTPUT
          echo -e "$URL_LIST" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Send LINE Notify
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_ACCESS_TOKEN }}
        run: |
          message="pytest-cov report deployment completed.

          Check URLs:
          ${{ steps.generate_url_list.outputs.url_list }}"

          curl -X POST https://notify-api.line.me/api/notify \
            -H "Authorization: Bearer $LINE_NOTIFY_TOKEN" \
            -F "message=${message}"
