name: Test Multi-OS

# ワークフローの処理の流れ:
# 1. トリガー条件:
#    - 手動実行
#    - mainブランチへのプルリクエスト
#    - mainブランチへのプッシュ（Version Updateワークフロー以外）
# 2. 複数の環境（OS、Pythonバージョン）でのテスト実行
# 3. テスト結果に基づくREADMEの更新
# 4. 全テスト結果の確認

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  test:
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !contains(github.ref, 'version-update')
    strategy:
      matrix:
        os: [macos-13, ubuntu-latest, windows-latest]
        python-version: ['3.11', '3.12']
    runs-on: ${{ matrix.os }}
    env:
      TZ: 'Asia/Tokyo'
    permissions:
      contents: write
      pull-requests: write
    steps:
      #- uses: actions/checkout@v4
      #- name: Set up Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: ${{matrix.python-version}}
      - name: Reuse Setup Python Workflow
        uses: ./.github/workflows/setup-python.yml
        with:
          python-version: ${{matrix.python-version}}
      - name: Set timezone on Windows
        if: runner.os == 'Windows'
        run: tzutil /s "Tokyo Standard Time"
        shell: cmd
      - name: Install poetry
        run: pip install poetry
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install
      - name: Run test
        id: pytest
        continue-on-error: true
        run: poetry run task test_gh_action_xml
      - name: Pytest coverage comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          pytest-xml-coverage-path: ./coverage.xml
          title: Coverage Report (${{ matrix.os }} / Python ${{ matrix.python-version }})
          badge-title: coverage
          hide-badge: false
          hide-report: false
          create-new-comment: false
          hide-comment: false
          report-only-changed-files: false
          remove-link-from-badge: false
          junitxml-path: ./pytest.xml
          junitxml-title: "Pytest Result Summary (os: ${{ matrix.os }} / python-version: ${{ matrix.python-version }})"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check test results
        if: steps.pytest.outcome == 'failure'
        run: |
          echo "Tests failed. This will prevent merging the pull request."
          exit 1
      - name: Save summary report
        run: |
          echo '${{ steps.coverageComment.outputs.summaryReport }}' > summary-report.md
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            pytest-coverage.txt
            coverage.xml
            pytest.xml
            summary-report.md

  update_readme:
    needs: test
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version') && !contains(github.ref, 'version-update') && always()
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Update README in coverage branch
        run: |
          # "coverage" ブランチが存在する場合はチェックアウト、存在しない場合は新規作成する
          if git ls-remote --heads origin coverage | grep coverage; then
            git checkout coverage
          else
            git checkout --orphan coverage
            git rm -rf .
          fi

          # README.mdのヘッダーとバッジを追加
          echo "# Coverage Reports" > README.md
          echo "[![](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml/badge.svg)](https://github.com/$GITHUB_REPOSITORY/actions/workflows/test_multi_os.yml)" >> README.md
          echo "" >> README.md

          # 最新のコミット情報をREADMEに追加
          commit_hash=${GITHUB_SHA::8}
          commit_link="[$commit_hash](https://github.com/$GITHUB_REPOSITORY/tree/$commit_hash)"
          echo -e "> [!Note]" >> README.md
          echo -e "> " >> README.md
          echo -e "> Commit: $commit_link" >> README.md
          echo -e "" >> README.md  # この行を追加

          # テスト対象外のファイルに関する注記を追加
          echo -e "> [!Important]" >> README.md
          echo -e "> The following file is intentionally excluded from test coverage:" >> README.md
          echo -e "> - \`project_a/staking/ton_whales_staking_dashboard.py\`" >> README.md
          echo -e "> " >> README.md
          echo -e "> This file contains complex external dependencies and is verified through manual and integration testing." >> README.md
          echo -e "> " >> README.md

          # macOS、Ubuntu、Windowsの各OSとPythonバージョンごとにカバレッジレポートを追加
          for os in macos-13 ubuntu-latest windows-latest; do
            for version in 3.11 3.12; do
              echo "## Coverage Report (os: $os / python-version: $version)" >> README.md
              if [ -f "coverage-data-$os-$version/summary-report.md" ]; then
                sed -e 's/^"//' -e 's/"$//' -e 's/\\"/"/g' -e 's/\\\\/\\/g' -e 's/\\n/\n/g' -e 's/\r$//' "coverage-data-$os-$version/summary-report.md" |
                sed -e 's/&lt;/</g' -e 's/&gt;/>/g' -e 's/&amp;/\&/g' |
                sed '/^$/N;/^\n$/D' |
                sed -e 's/^"//' -e 's/"$//' >> README.md
              else
                echo "No summary report found for $os - $version" >> README.md
              fi
              echo "" >> README.md
            done
          done

          # ファイルパスを修正する
          sed -i '
            s|/blob/\([a-f0-9]*\)/\([^"]*\)|/blob/\1/project_a/\2|g;
            s|/blob/\([a-f0-9]*\)/project_a/README\.md|/blob/\1/README.md|g
          ' README.md
      - name: Commit and push
        run: |
          # Gitのユーザー設定とコミット、ブランチへのプッシュ
          git config --local user.email "33836132+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          git commit -m "Update coverage for all environments"
          git push origin coverage

  check_all_tests:
    needs: test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check test results
        if: contains(needs.test.result, 'failure')
        run: |
          echo "Some tests failed. Please check the test results and fix any issues before merging."
          exit 1
