# pytest-testmon Deploy Multi-OS Workflow
#
# このワークフローの処理の流れ:
# 1. トリガー条件:
#    - mainブランチへのプッシュ時に起動
#    - Dependabotによる実行やバージョンバンプのコミットは除外
# 2. 複数の環境（OS、Pythonバージョン）でのセットアップと前回の.testmondataの取得
# 3. 各OS・Pythonバージョンごとに個別の.testmondataファイルを取得
# 4. pytest-testmonを使用してテスト実行
# 5. testmon結果の確認とテスト実行有無の判定
# 6. 更新された.testmondataファイルのアップロード
# 7. GitHub Pagesへの.testmondataファイルのデプロイ
# 8. pytest-covとpytest-htmlワークフローのトリガー

name: pytest-testmon Deploy Multi-OS

on:
  push:
    branches:
      - 'main'

jobs:
  test-and-deploy-testmon:
    # Dependabotによる実行やバージョンバンプのコミットを除外
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ['3.12']
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    # ジョブの出力を定義（テスト実行の有無と、OS・Pythonバージョンの情報を後続のジョブに伝える）
    outputs:
      matrix: ${{ toJson(strategy.matrix) }}
      os_list: ${{ toJson(strategy.matrix.os) }}
      python_versions: ${{ toJson(strategy.matrix.python-version) }}
      tests_executed: ${{ steps.pytest-testmon.outputs.tests_executed }}
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0  # 全履歴を取得

      # Pythonのセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      # タイムゾーンの設定
      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      # Poetryのインストール
      - name: Install poetry
        run: |
          pip install poetry
          echo "Poetry version: $(poetry --version)"

      # 依存関係のインストール
      - name: Install dependencies
        run: |
          poetry install
          echo "Installed dependencies:"
          poetry show --tree

      # 前回のtestmonデータの取得
      - name: Fetch previous testmon data
        shell: bash
        run: |
          echo "Fetching previous testmon data..."
          git fetch origin ghpages:ghpages || true
          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
          git checkout ghpages -- $folder_name/.testmondata || true
          if [ -f $folder_name/.testmondata ]; then
            echo "Previous testmon data found. Moving to current directory."
            mv $folder_name/.testmondata .testmondata
            rm -rf $folder_name
          else
            echo "No previous testmon data found for ${{ matrix.os }} with Python ${{ matrix.python-version }}."
          fi
        continue-on-error: true

      # testmonを使用してテストを実行
      - name: Run tests with testmon
        id: pytest-testmon
        shell: bash
        run: |
          echo "Running tests with testmon..."
          output=$(poetry run pytest --testmon -v)
          echo "$output"

          # testmonの出力をGitHub Actionsの出力変数に保存
          echo "testmon_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # 出力を確認して、テストが実行されなかった場合はフラグを設定
          if echo "$output" | grep -q "collected 0 items"; then
           echo "No tests executed. Skipping deployment and further workflows."
           echo "tests_executed=false" >> $GITHUB_OUTPUT
          else
           echo "Tests executed. Proceeding with deployment and further workflows."
           echo "tests_executed=true" >> $GITHUB_OUTPUT
          fi

      # デバッグ情報の出力
      - name: Debug Output
        run: |
          echo "Matrix: ${{ toJson(strategy.matrix) }}"
          echo "OS List: ${{ toJson(strategy.matrix.os) }}"
          echo "Python Versions: ${{ toJson(strategy.matrix.python-version) }}"

      # testmonデータのアップロード
      - name: Upload testmon data
        uses: actions/upload-artifact@v4.4.0
        with:
          name: testmon-data-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: .testmondata
          if-no-files-found: warn
        if: steps.pytest-testmon.outputs.tests_executed == 'true'

  deploy-testmon:
    needs: test-and-deploy-testmon
    if: needs.test-and-deploy-testmon.result == 'success'
    runs-on: ubuntu-latest
    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      # すべてのアーティファクトをダウンロード
      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: downloaded-artifacts

      # Gitの設定
      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Git configuration set."

      # 受け取った値のデバッグ出力
      - name: Debug Received Values
        run: |
          echo "Received Matrix: ${{ needs.test-and-deploy-testmon.outputs.matrix }}"
          echo "Received OS List: ${{ needs.test-and-deploy-testmon.outputs.os_list }}"
          echo "Received Python Versions: ${{ needs.test-and-deploy-testmon.outputs.python_versions }}"

      # testmonデータをGitHub Pagesにデプロイ
      - name: Deploy testmon data to GitHub Pages
        id: deploy_testmon
        env:
          MATRIX: ${{ needs.test-and-deploy-testmon.outputs.matrix }}
          OS_LIST: ${{ needs.test-and-deploy-testmon.outputs.os_list }}
          PYTHON_VERSIONS: ${{ needs.test-and-deploy-testmon.outputs.python_versions }}
        run: |
          echo "Deploying testmon data to GitHub Pages..."
          git fetch origin ghpages:ghpages || git checkout -b ghpages
          git checkout ghpages

          echo "MATRIX: $MATRIX"
          echo "OS_LIST: $OS_LIST"
          echo "PYTHON_VERSIONS: $PYTHON_VERSIONS"

          # 問題特定のためのデバッグ出力
          echo "Debug: MATRIX type: $(echo $MATRIX | jq -r 'type')"
          echo "Debug: OS_LIST type: $(echo $OS_LIST | jq -r 'type')"
          echo "Debug: PYTHON_VERSIONS type: $(echo $PYTHON_VERSIONS | jq -r 'type')"

          # nullチェックを追加
          if [ "$OS_LIST" = "null" ] || [ "$PYTHON_VERSIONS" = "null" ]; then
            echo "Error: OS_LIST or PYTHON_VERSIONS is null"
            exit 1
          fi

          os_list=$(echo $OS_LIST | jq -r '.[]')
          python_versions=$(echo $PYTHON_VERSIONS | jq -r '.[]')

          echo "Parsed OS_LIST: $os_list"
          echo "Parsed PYTHON_VERSIONS: $python_versions"

          changes_made=false
          for os in $os_list; do
            for python_version in $python_versions; do
              folder_name="testmon-data_${os}_python_${python_version}"
              artifact_folder="downloaded-artifacts/testmon-data-${os}-python-${python_version}"
              echo "Processing $os with Python ${python_version}..."
              echo "Checking for folder: ${artifact_folder}"
              if [ -d "${artifact_folder}" ]; then
                echo "Testmon data found for $os with Python ${python_version}, updating..."
                mkdir -p $folder_name
                mv "${artifact_folder}"/.testmondata "$folder_name/.testmondata" 2>/dev/null || true
                echo "Contents of $folder_name after move:"
                ls -la $folder_name
                git add $folder_name
                changes_made=true
              else
                echo "No testmon data found for $os with Python ${python_version}"
              fi
            done
          done

          if [ "$changes_made" = true ]; then
            echo "Changes made, committing and pushing..."
            git status
            git commit -m "Update testmon data on GitHub Pages"
            git push origin ghpages
            echo "deploy_status=updated" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "deploy_status=unchanged" >> $GITHUB_OUTPUT
          fi

      # デプロイされたファイルの一覧を表示
      - name: List deployed files
        if: steps.deploy_testmon.outputs.deploy_status == 'updated'
        run: |
          git checkout ghpages
          echo "Deployed testmon data files:"
          find . -name ".testmondata"
          echo "Contents of ghpages branch:"
          ls -R

  trigger-other-workflows:
    needs: [test-and-deploy-testmon, deploy-testmon]
    if: needs.test-and-deploy-testmon.result == 'success'
    runs-on: ubuntu-latest
    steps:
      # pytest-covワークフローのトリガー
      - name: Trigger pytest-cov workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-cov
          client-payload: '{"skip_tests": false}'

      # pytest-htmlワークフローのトリガー
      - name: Trigger pytest-html workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-html
          client-payload: '{"skip_tests": false}'

      # ワークフロートリガーのログ
      - name: Log workflow triggers
        run: |
          echo "Triggered pytest-cov and pytest-html workflows."
          echo "Check the Actions tab for these workflows to start."
