name: pytest-testmon Deploy Multi-OS

on:
  repository_dispatch:
    types:
      - test_pytest-testmon_deploy_multi_os

jobs:
  test-and-deploy-testmon:
    strategy:
      matrix:
        os: ${{ github.event.client_payload.os }}
        python-version: ${{ github.event.client_payload.python_versions }}
    runs-on: ${{ matrix.os }}
    env:
      TZ: "Asia/Tokyo"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      - name: Install poetry
        run: |
          pip install poetry
          echo "Poetry version: $(poetry --version)"

      - name: Install dependencies
        run: |
          poetry install
          echo "Installed dependencies:"
          poetry show --tree

      - name: Fetch previous testmon data
        shell: bash
        run: |
          echo "Fetching previous testmon data..."
          git fetch origin ghpages:ghpages || true
          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
          git checkout ghpages -- $folder_name/.testmondata || true
          if [ -f $folder_name/.testmondata ]; then
            echo "Previous testmon data found. Moving to current directory."
            mv $folder_name/.testmondata .testmondata
            rm -rf $folder_name
          else
            echo "No previous testmon data found for ${{ matrix.os }} with Python ${{ matrix.python-version }}."
          fi
        continue-on-error: true

      - name: Run tests with testmon
        id: pytest-testmon
        shell: bash
        run: |
          echo "Running tests with testmon..."
          output=$(poetry run pytest --testmon -v)
          echo "$output"
          if echo "$output" | grep -q "collected 0 items"; then
            echo "tests_executed=false" >> $GITHUB_OUTPUT
          else
            echo "tests_executed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create testmon directory and move .testmondata
        if: steps.pytest-testmon.outputs.tests_executed == 'true'
        shell: bash
        run: |
          echo "Creating testmon directory..."
          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
          mkdir -p "$folder_name"
          echo "Moving .testmondata file..."
          if [ -f ".testmondata" ]; then
            mv ".testmondata" "$folder_name/.testmondata" && echo "File moved successfully." || echo "Failed to move file."
          else
            echo "Warning: .testmondata file not found in root directory."
          fi
          echo "Contents of $folder_name:"
          ls -la "$folder_name"

      - name: Upload testmon data
        uses: actions/upload-artifact@v4.4.0
        with:
          name: testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}
          path: testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}/.testmondata
          if-no-files-found: warn
          include-hidden-files: true
          retention-days: 1
        if: steps.pytest-testmon.outputs.tests_executed == 'true'

      - name: Upload test execution status
        uses: actions/upload-artifact@v4
        with:
          name: test-status-${{ matrix.os }}-${{ matrix.python-version }}
          path: ${{ github.output }}

  analyze-results:
    needs: test-and-deploy-testmon
    runs-on: ubuntu-latest
    outputs:
      os_list: ${{ steps.analyze.outputs.os_list }}
      python_versions: ${{ steps.analyze.outputs.python_versions }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: test-statuses

      - name: Analyze test results
        id: analyze
        run: |
          os_list=()
          python_versions=()
          for status_file in test-statuses/test-status-*; do
            if grep -q "tests_executed=true" "$status_file"; then
              IFS='-' read -ra parts <<< "$(basename "$status_file")"
              os=${parts[2]}
              python_version=${parts[3]}
              os_list+=("$os")
              python_versions+=("$python_version")
            fi
          done
          echo "os_list=$(echo "${os_list[@]}" | jq -R -s -c 'split(" ") | unique')" >> $GITHUB_OUTPUT
          echo "python_versions=$(echo "${python_versions[@]}" | jq -R -s -c 'split(" ") | unique')" >> $GITHUB_OUTPUT

          # ログ出力
          echo "Analyzed OS list: ${os_list[@]}"
          echo "Analyzed Python versions: ${python_versions[@]}"

  deploy-testmon:
    needs: [test-and-deploy-testmon, analyze-results]
    if: needs.analyze-results.outputs.os_list != '[]' && needs.analyze-results.outputs.python_versions != '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Download testmon data
        uses: actions/download-artifact@v4.1.8
        with:
          path: downloaded-artifacts

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Git configuration set."

      - name: Deploy testmon data to GitHub Pages
        id: deploy_testmon
        run: |
          echo "Deploying testmon data to GitHub Pages..."
          git fetch origin ghpages:ghpages || git checkout -b ghpages
          git checkout ghpages

          changes_made=false
          os_list=${{ needs.analyze-results.outputs.os_list }}
          python_versions_list=${{ needs.analyze-results.outputs.python_versions }}

          for os in $(echo "$os_list" | jq -r '.[]'); do
            for python_version in $(echo "$python_versions_list" | jq -r '.[]'); do
              folder_name="testmon-data_${os}_python_${python_version}"
              artifact_folder="downloaded-artifacts/testmon-data_${os}_python_${python_version}"
              echo "Processing $os with Python $python_version..."
              if [ -d "$artifact_folder" ]; then
                if [ -f "${artifact_folder}/.testmondata" ]; then
                  echo "Changes detected for $os with Python $python_version, updating..."
                  mkdir -p "$folder_name"
                  cp "${artifact_folder}/.testmondata" "$folder_name/.testmondata"
                  git add "$folder_name"
                  changes_made=true
                else
                  echo "No .testmondata file found in $artifact_folder"
                fi
              else
                echo "Artifact folder not found: $artifact_folder"
              fi
            done
          done

          if [ "$changes_made" = true ]; then
            echo "Changes made, committing and pushing..."
            git commit -m "Update testmon data on GitHub Pages" || echo "No changes to commit"
            git push origin ghpages || echo "No changes to push"
            echo "deploy_status=updated" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "deploy_status=unchanged" >> $GITHUB_OUTPUT
          fi

      - name: List deployed files
        if: always()
        run: |
          git checkout ghpages
          echo "Deployed testmon data files:"
          find . -name ".testmondata"
          echo "Contents of ghpages branch:"
          ls -R

  trigger-other-workflows:
    needs: [analyze-results, deploy-testmon]
    if: needs.analyze-results.outputs.os_list != '[]' && needs.analyze-results.outputs.python_versions != '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pytest-cov workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-cov
          client-payload: |-
            {
              "os": ${{ needs.analyze-results.outputs.os_list }},
              "python_versions": ${{ needs.analyze-results.outputs.python_versions }},
              "skip_tests": false
            }

      - name: Trigger pytest-html workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-html
          client-payload: |-
            {
              "os": ${{ needs.analyze-results.outputs.os_list }},
              "python_versions": ${{ needs.analyze-results.outputs.python_versions }},
              "skip_tests": false
            }

      - name: Log workflow triggers
        run: |
          echo "Triggered pytest-cov and pytest-html workflows."
          echo "OS List: ${{ needs.analyze-results.outputs.os_list }}"
          echo "Python Versions: ${{ needs.analyze-results.outputs.python_versions }}"
          echo "Check the Actions tab for these workflows to start."
