name: pytest-testmon Deploy Multi-OS

on:
  push:
    branches:
      - 'main'

jobs:
  test-and-deploy-testmon:
    # Dependabotによる実行やバージョンバンプのコミットを除外
    if: github.actor != 'dependabot[bot]' && !startsWith(github.event.head_commit.message, 'Bump version')
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        python-version: ['3.12']
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    # ジョブの出力を定義（テスト実行の有無と、OS・Pythonバージョンの情報を後続のジョブに伝える）
    outputs:
      matrix: ${{ toJson(matrix) }}  # 修正された部分
      tests_executed: ${{ steps.pytest-testmon.outputs.tests_executed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0  # 全履歴を取得

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      - name: Install poetry
        run: |
          pip install poetry
          echo "Poetry version: $(poetry --version)"

      - name: Install dependencies
        run: |
          poetry install
          echo "Installed dependencies:"
          poetry show --tree

      - name: Fetch previous testmon data
        shell: bash
        run: |
          echo "Fetching previous testmon data..."
          git fetch origin ghpages:ghpages || true
          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
          git checkout ghpages -- $folder_name/.testmondata || true
          if [ -f $folder_name/.testmondata ]; then
            echo "Previous testmon data found. Moving to current directory."
            mv $folder_name/.testmondata .testmondata
            rm -rf $folder_name
          else
            echo "No previous testmon data found for ${{ matrix.os }} with Python ${{ matrix.python-version }}."
          fi
        continue-on-error: true

      - name: Run tests with testmon
        id: pytest-testmon
        shell: bash
        run: |
          echo "Running tests with testmon..."
          output=$(poetry run pytest --testmon -v)
          echo "$output"

          # testmonの出力をGitHub Actionsの出力変数に保存
          echo "testmon_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # 出力を確認して、テストが実行されなかった場合はフラグを設定
          if echo "$output" | grep -q "collected 0 items"; then
           echo "No tests executed. Skipping deployment and further workflows."
           echo "tests_executed=false" >> $GITHUB_OUTPUT
          else
           echo "Tests executed. Proceeding with deployment and further workflows."
           echo "tests_executed=true" >> $GITHUB_OUTPUT
          fi

      - name: Upload testmon data
        uses: actions/upload-artifact@v4.4.0
        with:
          name: testmon-data-${{ matrix.os }}-python-${{ matrix.python-version }}
          path: .testmondata
          if-no-files-found: warn
        if: steps.pytest-testmon.outputs.tests_executed == 'true'

  deploy-testmon:
    needs: test-and-deploy-testmon
    if: needs.test-and-deploy-testmon.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4.1.8
        with:
          path: downloaded-artifacts

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Git configuration set."

      - name: Deploy testmon data to GitHub Pages
        id: deploy_testmon
        env:
          MATRIX: ${{ fromJson(needs.test-and-deploy-testmon.outputs.matrix) }}  # 修正された部分
        run: |
          echo "Deploying testmon data to GitHub Pages..."
          git fetch origin ghpages:ghpages || git checkout -b ghpages
          git checkout ghpages

          echo "MATRIX: $MATRIX"

          # 問題特定のためのデバッグ出力
          echo "Debug: MATRIX type: $(echo $MATRIX | jq -r 'type')"

          # MATRIXがnullの場合のエラーハンドリング
          if [ "$MATRIX" = "null" ]; then
            echo "Error: MATRIX is null"
            exit 1
          fi

          os=${MATRIX.os}
          python_version=${MATRIX['python-version']}

          echo "Parsed OS: $os"
          echo "Parsed PYTHON_VERSION: $python_version"

          folder_name="testmon-data_${os}_python_${python_version}"
          artifact_folder="downloaded-artifacts/testmon-data-${os}-python-${python_version}"
          echo "Processing $os with Python ${python_version}..."
          echo "Checking for folder: ${artifact_folder}"
          if [ -d "${artifact_folder}" ]; then
            echo "Testmon data found for $os with Python ${python_version}, updating..."
            mkdir -p $folder_name
            mv "${artifact_folder}"/.testmondata "$folder_name/.testmondata" 2>/dev/null || true
            echo "Contents of $folder_name after move:"
            ls -la $folder_name
            git add $folder_name
            changes_made=true
          else
            echo "No testmon data found for $os with Python ${python_version}"
          fi

          if [ "$changes_made" = true ]; then
            echo "Changes made, committing and pushing..."
            git status
            git commit -m "Update testmon data on GitHub Pages"
            git push origin ghpages
            echo "deploy_status=updated" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "deploy_status=unchanged" >> $GITHUB_OUTPUT
          fi


      - name: List deployed files
        if: steps.deploy_testmon.outputs.deploy_status == 'updated'
        run: |
          git checkout ghpages
          echo "Deployed testmon data files:"
          find . -name ".testmondata"
          echo "Contents of ghpages branch:"
          ls -R

  trigger-other-workflows:
    needs: [test-and-deploy-testmon, deploy-testmon]
    if: needs.test-and-deploy-testmon.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pytest-cov workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-cov
          client-payload: '{"skip_tests": false}'

      - name: Trigger pytest-html workflow
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-html
          client-payload: '{"skip_tests": false}'

      - name: Log workflow triggers
        run: |
          echo "Triggered pytest-cov and pytest-html workflows."
          echo "Check the Actions tab for these workflows to start."
