name: pytest-testmon Deploy Multi-OS

on:
  repository_dispatch:
    types:
      - test_pytest-testmon_deploy_multi_os

jobs:
  test-and-deploy-testmon:
    strategy:
      matrix:
        os: ${{ github.event.client_payload.os }}
        python-version: ${{ github.event.client_payload.python_versions }}
    runs-on: ${{ matrix.os }}
    env:
      TZ: "Asia/Tokyo"
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set timezone
        uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Tokyo"
          timezoneMacos: "Asia/Tokyo"
          timezoneWindows: "Tokyo Standard Time"

      - name: Install poetry
        run: |
          pip install poetry
          echo "Poetry version: $(poetry --version)"

      - name: Install dependencies
        run: |
          poetry install
          echo "Installed dependencies:"
          poetry show --tree

      - name: Fetch previous testmon data
        shell: bash
        run: |
          echo "Fetching previous testmon data..."
          git fetch origin ghpages:ghpages || true
          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
          git checkout ghpages -- $folder_name/.testmondata || true
          if [ -f $folder_name/.testmondata ]; then
            echo "Previous testmon data found. Moving to current directory."
            mv $folder_name/.testmondata .testmondata
            rm -rf $folder_name
          else
            echo "No previous testmon data found for ${{ matrix.os }} with Python ${{ matrix.python-version }}."
          fi
        continue-on-error: true

      - name: Run tests with testmon
        id: pytest-testmon
        shell: bash
        run: |
          echo "Running tests with testmon..."
          output=$(poetry run pytest --testmon -v)
          echo "$output"

          echo "testmon_output<<EOF" >> $GITHUB_OUTPUT
          echo "$output" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          if echo "$output" | grep -q "collected 0 items"; then
            echo "No tests executed. Skipping deployment and further workflows."
            echo "tests_executed=false" >> $GITHUB_OUTPUT
          else
            echo "Tests executed. Proceeding with deployment and further workflows."
            echo "tests_executed=true" >> $GITHUB_OUTPUT
          fi

          # Store the result in a file for later use
          echo "${{ matrix.os }},${{ matrix.python-version }},${{ steps.pytest-testmon.outputs.tests_executed }}" >> test_results.txt

      - name: Create testmon directory and move .testmondata
        if: steps.pytest-testmon.outputs.tests_executed == 'true'
        shell: bash
        run: |
          echo "Creating testmon directory..."
          folder_name="testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}"
          mkdir -p "$folder_name"
          echo "Moving .testmondata file..."
          if [ -f ".testmondata" ]; then
            mv ".testmondata" "$folder_name/.testmondata" && echo "File moved successfully." || echo "Failed to move file."
          else
            echo "Warning: .testmondata file not found in root directory."
          fi
          echo "Contents of $folder_name:"
          ls -la "$folder_name"

      - name: Upload testmon data
        uses: actions/upload-artifact@v4.4.0
        with:
          name: testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}
          path: testmon-data_${{ matrix.os }}_python_${{ matrix.python-version }}/.testmondata
          if-no-files-found: warn
          include-hidden-files: true
          retention-days: 1
        if: steps.pytest-testmon.outputs.tests_executed == 'true'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.txt

  deploy-testmon:
    needs: test-and-deploy-testmon
    if: contains(needs.test-and-deploy-testmon.result, 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0

      - name: Download testmon data
        uses: actions/download-artifact@v4.1.8
        with:
          path: downloaded-artifacts

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo "Git configuration set."

      - name: Prepare os_list and python_versions
        run: |
          os_list='${{ join(github.event.client_payload.os, ' ') }}'
          python_versions_list='${{ join(github.event.client_payload.python_versions, ' ') }}'

          echo "OS List: $os_list"
          echo "Python Versions List: $python_versions_list"

          echo "os_list=$os_list" >> $GITHUB_ENV
          echo "python_versions_list=$python_versions_list" >> $GITHUB_ENV

      - name: Deploy testmon data to GitHub Pages
        id: deploy_testmon
        run: |
          echo "Deploying testmon data to GitHub Pages..."
          git fetch origin ghpages:ghpages || git checkout -b ghpages
          git checkout ghpages

          changes_made=false
          for os in $os_list; do
            for python_version in $python_versions_list; do
              folder_name="testmon-data_${os}_python_${python_version}"
              artifact_folder="downloaded-artifacts/testmon-data_${os}_python_${python_version}"
              echo "Processing $os with Python $python_version..."
              if [ -d "$artifact_folder" ]; then
                if [ -f "${artifact_folder}/.testmondata" ]; then
                  echo "Changes detected for $os with Python $python_version, updating..."
                  mkdir -p "$folder_name"
                  cp "${artifact_folder}/.testmondata" "$folder_name/.testmondata"
                  git add "$folder_name"
                  changes_made=true
                else
                  echo "No .testmondata file found in $artifact_folder"
                fi
              else
                echo "Artifact folder not found: $artifact_folder"
              fi
            done
          done

          if [ "$changes_made" = true ]; then
            echo "Changes made, committing and pushing..."
            git commit -m "Update testmon data on GitHub Pages" || echo "No changes to commit"
            git push origin ghpages || echo "No changes to push"
            echo "deploy_status=updated" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit"
            echo "deploy_status=unchanged" >> $GITHUB_OUTPUT
          fi

      - name: List deployed files
        if: always()
        run: |
          git checkout ghpages
          echo "Deployed testmon data files:"
          find . -name ".testmondata"
          echo "Contents of ghpages branch:"
          ls -R

  trigger-other-workflows:
    needs: [test-and-deploy-testmon, deploy-testmon]
    if: needs.test-and-deploy-testmon.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Collect valid configurations
        id: collect-configs
        run: |
          valid_os=()
          valid_python_versions=()

          while IFS=',' read -r os py_version status; do
            if [ "$status" = "true" ]; then
              valid_os+=("$os")
              valid_python_versions+=("$py_version")
            fi
          done < test_results.txt

          unique_os=$(echo "${valid_os[@]}" | tr ' ' '\n' | sort -u | jq -R . | jq -s .)
          unique_python_versions=$(echo "${valid_python_versions[@]}" | tr ' ' '\n' | sort -u | jq -R . | jq -s .)

          echo "valid_os=$unique_os" >> $GITHUB_OUTPUT
          echo "valid_python_versions=$unique_python_versions" >> $GITHUB_OUTPUT

      - name: Trigger pytest-cov workflow
        if: steps.collect-configs.outputs.valid_os != '[]' && steps.collect-configs.outputs.valid_python_versions != '[]'
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-cov
          client-payload: |-
            {
              "os": ${{ steps.collect-configs.outputs.valid_os }},
              "python_versions": ${{ steps.collect-configs.outputs.valid_python_versions }},
              "skip_tests": false
            }

      - name: Trigger pytest-html workflow
        if: steps.collect-configs.outputs.valid_os != '[]' && steps.collect-configs.outputs.valid_python_versions != '[]'
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: run-pytest-html
          client-payload: |-
            {
              "os": ${{ steps.collect-configs.outputs.valid_os }},
              "python_versions": ${{ steps.collect-configs.outputs.valid_python_versions }},
              "skip_tests": false
            }

      - name: Log workflow triggers
        run: |
          echo "Valid OS configurations: ${{ steps.collect-configs.outputs.valid_os }}"
          echo "Valid Python versions: ${{ steps.collect-configs.outputs.valid_python_versions }}"
          if [ "${{ steps.collect-configs.outputs.valid_os }}" != "[]" ] && [ "${{ steps.collect-configs.outputs.valid_python_versions }}" != "[]" ]; then
            echo "Triggered pytest-cov and pytest-html workflows for the above configurations."
            echo "Check the Actions tab for these workflows to start."
          else
            echo "No valid configurations found. Workflows were not triggered."
          fi
