name: Version Update and Release

on:
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of version update'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  update-version-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Get current version
        id: current_version
        run: echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT
      - name: Create new branch
        run: git checkout -b version-update-${{ github.run_id }}
      - name: Update version
        id: update_version
        run: |
          poetry version ${{ github.event.inputs.update_type }}
          echo "new_version=$(poetry version -s)" >> $GITHUB_OUTPUT
      - name: Commit changes
        run: |
          git add pyproject.toml
          git commit -m ":wrench: Bump version to ${{ steps.update_version.outputs.new_version }}" || echo "No changes to commit"
      - name: Push changes
        run: git push origin version-update-${{ github.run_id }}
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_url=$(gh pr create --title "Bump version to ${{ steps.update_version.outputs.new_version }}" --body "Automated version update" --base main --head version-update-${{ github.run_id }})
          echo "PR_URL=$pr_url" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        run: |
          changelog=$(git log --pretty=format:"- %s" v${{ steps.current_version.outputs.version }}..HEAD)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$changelog" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Release Draft
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: v${{ steps.update_version.outputs.new_version }}
          name: trial-test-v${{ steps.update_version.outputs.new_version }}
          body: |
            Changes in this Release:
            ${{ steps.changelog.outputs.changelog }}

            For full changes, see the [comparison view](${{ github.server_url }}/${{ github.repository }}/compare/v${{ steps.current_version.outputs.version }}..v${{ steps.update_version.outputs.new_version }})
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print PR URL
        run: echo "Pull Request created at ${{ env.PR_URL }}"
